### ISSUE TITLE
문의 프레펩 사용관련

### ISSUE THREAD

**Issue by CPT-BJ** [lunetis/AceCombatZERO#1]
안녕하십니까. 선생님께서 깃허브에 올려주신 Operation Zero를 보고 현재 만들고 있는 다른 프로젝트에 참고를 잘 하고 있는 대학원생입니다.
이렇게 메일을 보내드린 이유는 질문을 드리고 싶은사항이 있어서 글을 남겨드렸습니다.
다른곳에서 사용하신 에셋들에 대하여 출처를 남겨주셨는데, 선생님의 유니티 파일을 받아서 유니티상에서 구현해보고 싶은데, 아래 사진과 같이 해당 Prefab을 찾을 수 없다고 표시가 되는데, 이런 경우에는 출처를 밝혀주신곳에서 다운받은후에 prefab으로 변환하여 폴더에 넣어줘야하는것인지 궁금합니다. 감사합니다.
<img width="883" alt="스크린샷 2022-05-09 오후 5 02 11" src="https://user-images.githubusercontent.com/101859950/167368871-3c48acd5-8242-4c3b-b839-c19eef241236.png">

**Comment by lunetis** [comment]
안녕하세요. 3D 모델 프리팹을 찾을 수 없는 에러 메시지에 대한 이슈를 올려주셨는데요,
해당 문제가 발생하는 모델들은 모두 .blend 파일이고, Blender가 설치되지 않으면 유니티에서 해당 모델에 대한 정보를 제대로 확인하지 못해서 발생하는 이슈로 보입니다.

저도 새로운 환경에서 프로젝트를 열어봤을 때 말씀해주신 것과 동일한 문제가 발생했고,
Blender 설치 후 Unity 에디터에서 Reimport All를 실행한 후에는 에러가 발생하지 않았습니다.
그리고 Blender를 이미 설치한 환경에서는 프로젝트를 최초로 열었을 때 위와 같은 문제가 발생하지 않았습니다.
(*확인 과정에 사용한 에디터 버전은 2020.3.31f1로, 프로젝트 진행 시에 사용했던 에디터 버전(2020.2.3)과 다릅니다.)

[https://www.blender.org/download/](https://www.blender.org/download/)
위 링크에서 Blender를 설치한 후, Unity 에디터 메뉴에서 Assets - Reimport All 을 실행해서
문제가 계속 발생하는지 확인해보실 수 있나요?

**Comment by CPT-BJ** [comment]
선생님께서 알려주신 방법을 통해서 import가 되지 않던 이슈를 해결했습니다. 친절하신 답변 대단히 감사드립니다. 연구에 잘 활용하도록하겠습니다!

**Comment by lunetis** [comment]
Blender가 설치되지 않은 환경에서 프로젝트를 여는 분이 많을 것 같아서, 해당 이슈와 해결 방법은 README에 추가해두었습니다.
소중한 이슈 제보 감사드립니다!
